name: Tests

on:
  push:
    branches: [ main, 'dev**' ]
  pull_request:
    branches: [ main, 'dev**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Python Configuration ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov pytest-homeassistant-custom-component
        pip install homeassistant
        
    - name: Running the tests
      run: |
        python -m pytest tests/ -v --asyncio-mode=auto --cov=custom_components/ihomma_sml --cov-report=xml
        
    - name: Uploading code coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true